apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: config-test
spec:
  build:
    useBuildKit: true
  environments:
    - name: nils
      build:
        from: feat/*
    - name: richard
      build:
        from: feat/*        
    - name: dev
      build:
        from: main
    - name: qa
      build:
        from: qa
    - name: qa2
      build:
        from: qa        
    - name: prod
      build:
        from: release
  
  components:
    - name: api
      ports:
        - name: http
          port: 5000
      publicPort: http
      resources:
        requests:
          cpu: 10m
          memory: 20M